name: Release ZIP (single final zip)

on:
  push:
    tags:
      - "release-v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Derive version and names
        id: vars
        run: |
          TAG="${{ github.ref_name }}"  
          VERSION="${TAG#release-}"       
          ZIP="laqirapay-${VERSION}.zip"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "zip=${ZIP}" >> "$GITHUB_OUTPUT"

      - name: Prepare folder (copy sources into ./laqirapay)
        run: |
          rm -rf laqirapay
          mkdir -p laqirapay
          rsync -a ./ laqirapay/ \
            --exclude '.git' \
            --exclude '.github/workflows' \
            --exclude '.gitignore' \
            --exclude '.gitattributes' || true

      - name: Create final zip (root folder = laqirapay)
        run: |
          zip -r "${{ steps.vars.outputs.zip }}" laqirapay

      - name: Publish GitHub Release with final ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: laqirapay ${{ steps.vars.outputs.version }}
          generate_release_notes: true
          files: ${{ steps.vars.outputs.zip }}
