name: Build Release Zip

on:
  push:
    tags:
      - "release-v*"

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Derive version and artifact name
        id: vars
        run: |
          TAG="${{ github.ref_name }}"     
          VERSION="${TAG#release-}"    
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "artifact=laqirapay-$VERSION" >> "$GITHUB_OUTPUT"

      - name: Prepare folder (copy sources into laqirapay/)
        run: |
          mkdir -p laqirapay
          rsync -a ./ laqirapay/ \
            --exclude '.git' \
            --exclude '.github/workflows' \
            --exclude '.gitignore' \
            --exclude '.gitattributes' || true

      - name: Upload artifact (single zip containing laqirapay/)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.artifact }}
          path: laqirapay/
          if-no-files-found: error
