name: Build Release Zip

on:
  push:
    tags:
      - "release-v*"

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare folder
        run: |
          mkdir -p laqirapay
          cp -r ./* laqirapay/ || true
          cp -r ./.??* laqirapay/ || true
          rm -rf laqirapay/.git

      - name: Create zip
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/release-}
          ZIP_NAME="laqirapay-${TAG_NAME}.zip"
          zip -r "$ZIP_NAME" laqirapay

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: laqirapay-*.zip